### ISSUE TITLE
Implement Firebase Cloud Messaging support

### ISSUE THREAD

**Issue by link2xt** [chatmail/notifiers#31]
`/notify` endpoint should support Firebase Cloud Messaging.
Currently unprefixed tokens go to APNS production server and tokens with `sandbox:` prefix go to APNS sandbox server. Tokens with `fcm-*:` prefix should go to FCM server.

We can take the code from https://github.com/threema-ch/push-relay/blob/a5ef862ec5cccdd5d738c49042d60595068adbc4/src/push/fcm.rs (Apache/MIT licensed like Rust).
It is however outdated, there is a guide for migrating to modern REST API at https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by r10s** [comment]
> Tokens with fcm: prefix should go to FCM server.

i practise, we want to support also beta-versions for FCM, so i added the applicationId to the prefix.

this results in the following relevant ones:

- `fcm-chat.delta:` (our gplay, amazon etc. .apk)

- `fcm-com.b44t.messenger.beta:` (our betas, the ones with "DEV" in the icon, i assume also nightlies and PR assets are build like that)

to make things simple in the app for the beginning (and to postpone dealing with build issues), there is also  `fcm-com.b44t.messenger:` and `fcm-chat.delta.beta:` - which can be ignored. same as all other `fcm-*:` prefixes.

`com.b44t.messenger` is f-droid and could work in theory, however, i assume we want to skip FCM for f-droid for $reasons completely and not even add the libs ;)

**Comment by r10s** [comment]
k, then we can probably remove them from the `fcm:` prefix - that might also make adaption wrt  deltalab easier, but let's first see to get a roundtrip working
